services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aislides
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  tex-pdf:
    build:
      context: .
      dockerfile: Dockerfile.tex
    volumes:
      - ./generated_files/pdf:/workspace
    working_dir: /workspace
    command: tail -f /dev/null  # Keep container running
    restart: unless-stopped

volumes:
  postgres_data:
