[project]
name = "ppt-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=22.0,<25.0",
    "colorlog>=6.9.0",
    "fastapi>=0.121.2",
    "httpx>=0.28.1",
    "pillow>=11.3.0",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.11.7",
    "pydantic-ai>=1.0.4",
    "pydantic-ai-slim[duckduckgo]>=1.0.4",
    "pydantic-ai-slim[groq]>=1.0.4",
    "pylatex>=1.4.2",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "python-pptx>=1.0.2",
    "sqlalchemy>=2.0.44",
    "tavily-python>=0.7.14",
    "uvicorn>=0.35.0",
    "toons>=0.4.0",
    "azure-storage-blob>=12.28.0",
    "azure-identity>=1.25.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
