const SlideInspector = () => {
  return (
    <div className="h-full w-full flex flex-col bg-background">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border flex-shrink-0">
        <h2 className="text-base font-semibold text-text-primary">
          Slide Editor
        </h2>
        <div className="flex items-center gap-2">
          <div className="text-xs text-text-muted px-2 py-1 bg-background-elevated rounded-md">
            Slide 1 of 10
          </div>
        </div>
      </div>

      {/* Slide Context - Preview of current slide */}
      <div className="px-3 py-4 border-b border-border flex-shrink-0">
        <div className="text-xs text-text-secondary font-medium mb-2">Current Slide</div>
        <div className="bg-background-elevated rounded-md p-3">
          <h3 className="text-sm font-medium text-text-primary mb-1.5">
            Introduction to AI
          </h3>
          <p className="text-xs text-text-muted leading-relaxed">
            Overview of artificial intelligence and its applications in modern technology
          </p>
        </div>
      </div>

      {/* Edit Prompt Area */}
      <div className="flex-1 overflow-y-auto px-3 py-4">
        <div className="mb-4">
          <label className="text-xs text-text-secondary font-medium mb-2 block">
            Edit This Slide
          </label>
          <textarea
            className="w-full h-28 bg-background-elevated border border-border rounded-md p-3 text-sm text-text-primary placeholder-text-muted resize-none outline-none focus:border-primary transition-colors"
            placeholder="Describe how you want to modify this slide... (e.g., 'Add more details about machine learning')"
          />
        </div>

        {/* Quick Actions */}
        <div className="mb-4">
          <div className="text-xs text-text-secondary font-medium mb-2">Quick Actions</div>
          <div className="flex flex-wrap gap-2">
            <button className="px-2.5 py-1.5 text-xs rounded-md bg-background-elevated border border-border text-text-secondary hover:border-primary hover:text-primary transition-colors">
              Add detail
            </button>
            <button className="px-2.5 py-1.5 text-xs rounded-md bg-background-elevated border border-border text-text-secondary hover:border-primary hover:text-primary transition-colors">
              Simplify
            </button>
            <button className="px-2.5 py-1.5 text-xs rounded-md bg-background-elevated border border-border text-text-secondary hover:border-primary hover:text-primary transition-colors">
              Add examples
            </button>
            <button className="px-2.5 py-1.5 text-xs rounded-md bg-background-elevated border border-border text-text-secondary hover:border-primary hover:text-primary transition-colors">
              Change tone
            </button>
          </div>
        </div>

        {/* Context Slides */}
        <div className="space-y-3">
          <div>
            <div className="text-xs text-text-secondary font-medium mb-2">Previous Slide</div>
            <div className="bg-background-elevated/50 rounded-md p-2.5 border border-border/50">
              <h4 className="text-xs font-medium text-text-muted mb-0.5">
                Title Slide
              </h4>
              <p className="text-xs text-text-muted/70">
                AI Presentation - Generated by AI
              </p>
            </div>
          </div>
          <div>
            <div className="text-xs text-text-secondary font-medium mb-2">Next Slide</div>
            <div className="bg-background-elevated/50 rounded-md p-2.5 border border-border/50">
              <h4 className="text-xs font-medium text-text-muted mb-0.5">
                AI Applications
              </h4>
              <p className="text-xs text-text-muted/70">
                Real-world use cases of AI
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Actions Footer */}
      <div className="px-3 py-3 border-t border-border flex-shrink-0">
        <div className="flex gap-2">
          <button className="flex-1 px-3 py-2 bg-primary hover:bg-primary-hover text-white text-sm rounded-md font-medium transition-colors">
            Apply Changes
          </button>
          <button className="px-3 py-2 bg-background-elevated hover:bg-muted border border-border text-text-secondary text-sm rounded-md transition-colors">
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
};

export default SlideInspector;
